lib/execjs/runtimes.rb

Use node.js if available instead of JavascriptCore on OSX.

---

lib/execjs/external_runtime.rb

This allows scripts to be detected as a runtime, for circumstances where the actual binary is not in PATH, but a forwarding script is.

Support checking the PATHEXT variable on Windows.

---

.travis.yml
README.md
lib/execjs/runtimes.rb
lib/execjs/support/v8_runner.js

`rake test` passes here with v8-4.5.103.29 on Mac OS X.
It also should be added to travis, but I'm not really sure how it should be done (plain `sudo apt-get install v8` in `before_install` or somewhat else).

Add direct V8 support (via `d3`)

---

lib/execjs/disabled_runtime.rb
lib/execjs/duktape_runtime.rb
lib/execjs/external_runtime.rb
lib/execjs/module.rb
lib/execjs/ruby_racer_runtime.rb
lib/execjs/ruby_rhino_runtime.rb
lib/execjs/runtime.rb
test/test_execjs.rb

An `options` hash is already part of the `Context` argument list, but isn't totally plumbed all the way through.
It'd be great if we passed the options all the way down. This would allow for implementation specific flags such as timeouts.
``` ruby
ExecJS.eval("superSlow()", timeout: 3)
```
-
CC: @rafaelfranca @guilleiguaran

Allow for runtime specific option flags

---

lib/execjs/support/jsc_runner.js
lib/execjs/support/node_runner.js
test/test_execjs.rb

Shadowed globals maybe also accessed via `this.console`. This normalizes these globals across all runners. See FAQ (https://github.com/rails/execjs#faq) for why these globals should not be exposed during evaluation.
Related #42.

Undefine globals, not just shadow

---

lib/execjs/runtimes.rb

I had [problem in AutoprefixerRails](https://travis-ci.org/ai/autoprefixer-rails/jobs/279410685) when I set `EXECJS_RUNTIME=` (empty value).
I set the [empty value](https://github.com/ai/autoprefixer-rails/blob/91bcfcda9f9ffc7cdb9c1b11c84db1496a8c7939/.travis.yml#L20) to override previous value for tests.
@rafaelfranca what do you think about this fix?

Fix for empty EXECJS_RUNTIME

---

lib/execjs/duktape_runtime.rb
lib/execjs/ruby_racer_runtime.rb
lib/execjs/runtime.rb
test/test_execjs.rb

The following pull request:
- Adds documentation for Context#exec, #eval and #call
- Explicitly allows for Context#call to accept any function expression
- Makes Duktape respect this behavior

Improved documentation/tests for exec/eval/call

---

lib/execjs/external_runtime.rb

fixes https://github.com/rails/execjs/issues/91

fix deprecation warning ruby 2.7+

---

lib/execjs/external_runtime.rb
lib/execjs/graaljs_runtime.rb
lib/execjs/ruby_rhino_runtime.rb
test/test_execjs.rb

@byroot Could you review and merge? :)
@bjfish noticed `barber` and/or Discourse is relying on this.
For curiosity I also tried what happens if we pass `Object.new` to JS and on miniracer & node it just passes it as a String with `.to_s` like `JSON.dump` does (e.g. `"#<Object:0x0000000001d05718>"`). On duktape it gives `TypeError: cannot convert Object` and on the Graal.js backend it gives `TypeError: Unknown how to convert to JS: #<Object:0x1ad8>`.
I think the TypeError is good there, JSON just using `to_s` seems rather unexpected in general, so I think let's keep that as-is.

Add test for passing Symbol to JS and fix it for GraalJSRuntime

---

lib/execjs/graaljs_runtime.rb

* Foreign exceptions are no longer translated to ::RuntimeError but
remain as foreign exceptions and are given the class Polyglot::ForeignException.
* The backtrace can be nil, notably when throwing a JS string.
cc @byroot

Adapt ExecJS::GraalJSRuntime to foreign exception changes in TruffleRuby

---

lib/execjs/graaljs_runtime.rb
test/test_execjs.rb

A follow-up of #115, somehow I missed that Symbol should be treated the same as String.
The added test fails without the fix (because it ends up calling Ruby's `String#slice` and not JS's `String.prototype.slice()`), and passes with the fix.
cc FYI @bjfish

Convert Symbol explicitly to a JS String and add test

---

lib/execjs/external_runtime.rb

This makes it hard to track down the source of allocations and such when profiling.

Avoid anonymous eval

---

README.md

`discourse/mini_racer` -> `rubyjs/mini_racer`
Don't know when, but mini_racer lives at https://github.com/rubyjs/mini_racer

Update URL to mini_racer GH repository

---

lib/execjs/external_runtime.rb

This fixes CI failures on macos:
https://github.com/rails/execjs/actions/runs/5141287879/jobs/9253613193

Skip `eval code@` line thrown by Apple JavaScriptCore

---

.github/workflows/ci.yml

because truffleruby+graalvm 23.0.0-preview1 aborts with `gu: command not found` https://github.com/rails/execjs/actions/runs/5142014882/jobs/9255214275
/cc @eregon

CI against stable version of truffleruby+graalvm (22.3.1) for now

---

lib/execjs/external_runtime.rb
test/test_execjs.rb

Fix: https://github.com/rails/execjs/issues/130

Handle Bun priting loaded env variables on STDERR

---

.github/workflows/ci.yml
lib/execjs/graaljs_runtime.rb

The way to install GraalJS changed, and this is now documented in TruffleRuby docs.

Updates for TruffleRuby 23.1

---

lib/execjs/support/bun_runner.js

I encountered this issue in bun https://github.com/oven-sh/bun/issues/6573 and I tried using `Bun.write` instead of `process.stdout.write` then I realized that above issue does not occurs. So I replaced with Bun.write to avoid this issue and potential performance optimize since Bun.write uses faster system call than normal one.

Use Bun.write(Bun.stdout, '') for output in Bun executor

---

lib/execjs/support/bun_runner.js
test/test_execjs.rb

This PR adds support for async/await and promises for the Bun runner. 
This allows for importing libraries using dynamic imports:
```
const Plot = await import("@observablehq/plot")
```

Add async/await & promise support to Bun runner

---

lib/execjs.rb
test/test_execjs.rb

Changed the way `ExecJS.runtime` is defined so that `Runtimes.autodetect` is called only when calling `ExecJS.runtime` and not when requiring the gem itself.
For the context, we work on a Rails application named [Osuny](https://github.com/noesya/osuny) and for optimization purposes, we were working on reducing the slug size of the application image on our hosting platform Scalingo.
For this, we wanted to remove the folder containing the `node` binary as it is only used for asset compilation, and thus useless for application runtime. But removing it caused the application to fail on boot as ExecJS was trying to detect a JS runtime when starting the application.
We managed to trace back the source to the `bootstrap` gem being required, and following its dependencies, requiring …

Prevent runtime autodetection on gem require
